spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:mem:test
    jpa:
        hibernate:
            ddl-auto: create  # (1) 스키마 자동 생성
        show-sql: true      # (2) SQL 쿼리 출력
        properties:
            hibernate:
                format_sql: true  # (3) SQL pretty print
    sql:
        init:
            schema-locations: classpath*:db/h2/schema.sql
            data-locations: classpath*:db/h2/data.sql
    security:
      oauth2:
        client:
            registration:
              google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
    level:
        org:
            springframework:
                orm:
                    jpa : DEBUG

jwt:
    key: ${JWT_SECRET_KEY}
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420
